//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AlgorithmatMVC.AlgorithmatOnline {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlgorithmatOnlineServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AlgorithmatOnlineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSiteReadingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEditContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEditPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEditImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEditFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AlgorithmatOnlineService() {
            this.Url = global::AlgorithmatMVC.Properties.Settings.Default.AlgorithmatMVC_AlgorithmatOnline_AlgorithmatOnlineService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event RegisterCustomerCompletedEventHandler RegisterCustomerCompleted;
        
        /// <remarks/>
        public event UploadDataCompletedEventHandler UploadDataCompleted;
        
        /// <remarks/>
        public event UploadSiteReadingsCompletedEventHandler UploadSiteReadingsCompleted;
        
        /// <remarks/>
        public event AddEditContentCompletedEventHandler AddEditContentCompleted;
        
        /// <remarks/>
        public event DeleteContentCompletedEventHandler DeleteContentCompleted;
        
        /// <remarks/>
        public event SearchContentCompletedEventHandler SearchContentCompleted;
        
        /// <remarks/>
        public event AddEditPageCompletedEventHandler AddEditPageCompleted;
        
        /// <remarks/>
        public event DeletePageCompletedEventHandler DeletePageCompleted;
        
        /// <remarks/>
        public event SearchPageCompletedEventHandler SearchPageCompleted;
        
        /// <remarks/>
        public event AddEditImageCompletedEventHandler AddEditImageCompleted;
        
        /// <remarks/>
        public event DeleteImageCompletedEventHandler DeleteImageCompleted;
        
        /// <remarks/>
        public event SearchImageCompletedEventHandler SearchImageCompleted;
        
        /// <remarks/>
        public event AddEditFileCompletedEventHandler AddEditFileCompleted;
        
        /// <remarks/>
        public event DeleteFileCompletedEventHandler DeleteFileCompleted;
        
        /// <remarks/>
        public event SearchFileCompletedEventHandler SearchFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegisterCustomer(string strMail, string strPass) {
            object[] results = this.Invoke("RegisterCustomer", new object[] {
                        strMail,
                        strPass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterCustomerAsync(string strMail, string strPass) {
            this.RegisterCustomerAsync(strMail, strPass, null);
        }
        
        /// <remarks/>
        public void RegisterCustomerAsync(string strMail, string strPass, object userState) {
            if ((this.RegisterCustomerOperationCompleted == null)) {
                this.RegisterCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterCustomerOperationCompleted);
            }
            this.InvokeAsync("RegisterCustomer", new object[] {
                        strMail,
                        strPass}, this.RegisterCustomerOperationCompleted, userState);
        }
        
        private void OnRegisterCustomerOperationCompleted(object arg) {
            if ((this.RegisterCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCustomerCompleted(this, new RegisterCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadData(System.Data.DataSet dsTemp) {
            object[] results = this.Invoke("UploadData", new object[] {
                        dsTemp});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadDataAsync(System.Data.DataSet dsTemp) {
            this.UploadDataAsync(dsTemp, null);
        }
        
        /// <remarks/>
        public void UploadDataAsync(System.Data.DataSet dsTemp, object userState) {
            if ((this.UploadDataOperationCompleted == null)) {
                this.UploadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadDataOperationCompleted);
            }
            this.InvokeAsync("UploadData", new object[] {
                        dsTemp}, this.UploadDataOperationCompleted, userState);
        }
        
        private void OnUploadDataOperationCompleted(object arg) {
            if ((this.UploadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadDataCompleted(this, new UploadDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadSiteReadings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadSiteReadings(int intSiteID, string strUser, string strPass, System.Data.DataSet dsReadings) {
            object[] results = this.Invoke("UploadSiteReadings", new object[] {
                        intSiteID,
                        strUser,
                        strPass,
                        dsReadings});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSiteReadingsAsync(int intSiteID, string strUser, string strPass, System.Data.DataSet dsReadings) {
            this.UploadSiteReadingsAsync(intSiteID, strUser, strPass, dsReadings, null);
        }
        
        /// <remarks/>
        public void UploadSiteReadingsAsync(int intSiteID, string strUser, string strPass, System.Data.DataSet dsReadings, object userState) {
            if ((this.UploadSiteReadingsOperationCompleted == null)) {
                this.UploadSiteReadingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSiteReadingsOperationCompleted);
            }
            this.InvokeAsync("UploadSiteReadings", new object[] {
                        intSiteID,
                        strUser,
                        strPass,
                        dsReadings}, this.UploadSiteReadingsOperationCompleted, userState);
        }
        
        private void OnUploadSiteReadingsOperationCompleted(object arg) {
            if ((this.UploadSiteReadingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSiteReadingsCompleted(this, new UploadSiteReadingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEditContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddEditContent(System.Data.DataSet dsContent) {
            object[] results = this.Invoke("AddEditContent", new object[] {
                        dsContent});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddEditContentAsync(System.Data.DataSet dsContent) {
            this.AddEditContentAsync(dsContent, null);
        }
        
        /// <remarks/>
        public void AddEditContentAsync(System.Data.DataSet dsContent, object userState) {
            if ((this.AddEditContentOperationCompleted == null)) {
                this.AddEditContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEditContentOperationCompleted);
            }
            this.InvokeAsync("AddEditContent", new object[] {
                        dsContent}, this.AddEditContentOperationCompleted, userState);
        }
        
        private void OnAddEditContentOperationCompleted(object arg) {
            if ((this.AddEditContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEditContentCompleted(this, new AddEditContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteContent(int intContentetID) {
            this.Invoke("DeleteContent", new object[] {
                        intContentetID});
        }
        
        /// <remarks/>
        public void DeleteContentAsync(int intContentetID) {
            this.DeleteContentAsync(intContentetID, null);
        }
        
        /// <remarks/>
        public void DeleteContentAsync(int intContentetID, object userState) {
            if ((this.DeleteContentOperationCompleted == null)) {
                this.DeleteContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteContentOperationCompleted);
            }
            this.InvokeAsync("DeleteContent", new object[] {
                        intContentetID}, this.DeleteContentOperationCompleted, userState);
        }
        
        private void OnDeleteContentOperationCompleted(object arg) {
            if ((this.DeleteContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteContentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchContent(int intContentID, int intType, string strDesc, int intMinID, int intMaxID) {
            object[] results = this.Invoke("SearchContent", new object[] {
                        intContentID,
                        intType,
                        strDesc,
                        intMinID,
                        intMaxID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchContentAsync(int intContentID, int intType, string strDesc, int intMinID, int intMaxID) {
            this.SearchContentAsync(intContentID, intType, strDesc, intMinID, intMaxID, null);
        }
        
        /// <remarks/>
        public void SearchContentAsync(int intContentID, int intType, string strDesc, int intMinID, int intMaxID, object userState) {
            if ((this.SearchContentOperationCompleted == null)) {
                this.SearchContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchContentOperationCompleted);
            }
            this.InvokeAsync("SearchContent", new object[] {
                        intContentID,
                        intType,
                        strDesc,
                        intMinID,
                        intMaxID}, this.SearchContentOperationCompleted, userState);
        }
        
        private void OnSearchContentOperationCompleted(object arg) {
            if ((this.SearchContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchContentCompleted(this, new SearchContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEditPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddEditPage(System.Data.DataSet dsPage) {
            this.Invoke("AddEditPage", new object[] {
                        dsPage});
        }
        
        /// <remarks/>
        public void AddEditPageAsync(System.Data.DataSet dsPage) {
            this.AddEditPageAsync(dsPage, null);
        }
        
        /// <remarks/>
        public void AddEditPageAsync(System.Data.DataSet dsPage, object userState) {
            if ((this.AddEditPageOperationCompleted == null)) {
                this.AddEditPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEditPageOperationCompleted);
            }
            this.InvokeAsync("AddEditPage", new object[] {
                        dsPage}, this.AddEditPageOperationCompleted, userState);
        }
        
        private void OnAddEditPageOperationCompleted(object arg) {
            if ((this.AddEditPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEditPageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletePage(int intPageID) {
            this.Invoke("DeletePage", new object[] {
                        intPageID});
        }
        
        /// <remarks/>
        public void DeletePageAsync(int intPageID) {
            this.DeletePageAsync(intPageID, null);
        }
        
        /// <remarks/>
        public void DeletePageAsync(int intPageID, object userState) {
            if ((this.DeletePageOperationCompleted == null)) {
                this.DeletePageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePageOperationCompleted);
            }
            this.InvokeAsync("DeletePage", new object[] {
                        intPageID}, this.DeletePageOperationCompleted, userState);
        }
        
        private void OnDeletePageOperationCompleted(object arg) {
            if ((this.DeletePageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchPage(int intPageID, string strDesc, string strTitleA, string strURLA) {
            object[] results = this.Invoke("SearchPage", new object[] {
                        intPageID,
                        strDesc,
                        strTitleA,
                        strURLA});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchPageAsync(int intPageID, string strDesc, string strTitleA, string strURLA) {
            this.SearchPageAsync(intPageID, strDesc, strTitleA, strURLA, null);
        }
        
        /// <remarks/>
        public void SearchPageAsync(int intPageID, string strDesc, string strTitleA, string strURLA, object userState) {
            if ((this.SearchPageOperationCompleted == null)) {
                this.SearchPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchPageOperationCompleted);
            }
            this.InvokeAsync("SearchPage", new object[] {
                        intPageID,
                        strDesc,
                        strTitleA,
                        strURLA}, this.SearchPageOperationCompleted, userState);
        }
        
        private void OnSearchPageOperationCompleted(object arg) {
            if ((this.SearchPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchPageCompleted(this, new SearchPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEditImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddEditImage(System.Data.DataSet dsImage) {
            this.Invoke("AddEditImage", new object[] {
                        dsImage});
        }
        
        /// <remarks/>
        public void AddEditImageAsync(System.Data.DataSet dsImage) {
            this.AddEditImageAsync(dsImage, null);
        }
        
        /// <remarks/>
        public void AddEditImageAsync(System.Data.DataSet dsImage, object userState) {
            if ((this.AddEditImageOperationCompleted == null)) {
                this.AddEditImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEditImageOperationCompleted);
            }
            this.InvokeAsync("AddEditImage", new object[] {
                        dsImage}, this.AddEditImageOperationCompleted, userState);
        }
        
        private void OnAddEditImageOperationCompleted(object arg) {
            if ((this.AddEditImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEditImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteImage(int intImageID) {
            this.Invoke("DeleteImage", new object[] {
                        intImageID});
        }
        
        /// <remarks/>
        public void DeleteImageAsync(int intImageID) {
            this.DeleteImageAsync(intImageID, null);
        }
        
        /// <remarks/>
        public void DeleteImageAsync(int intImageID, object userState) {
            if ((this.DeleteImageOperationCompleted == null)) {
                this.DeleteImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteImageOperationCompleted);
            }
            this.InvokeAsync("DeleteImage", new object[] {
                        intImageID}, this.DeleteImageOperationCompleted, userState);
        }
        
        private void OnDeleteImageOperationCompleted(object arg) {
            if ((this.DeleteImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteImageCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchImage(int intID, string strIDs, string strTitle, string strDesc, int intCountryID, int intSubjectID, bool blIsDateRange, System.DateTime dtStartDate, System.DateTime dtEndDate, int intImageType, int intSize, int intLanguage) {
            object[] results = this.Invoke("SearchImage", new object[] {
                        intID,
                        strIDs,
                        strTitle,
                        strDesc,
                        intCountryID,
                        intSubjectID,
                        blIsDateRange,
                        dtStartDate,
                        dtEndDate,
                        intImageType,
                        intSize,
                        intLanguage});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchImageAsync(int intID, string strIDs, string strTitle, string strDesc, int intCountryID, int intSubjectID, bool blIsDateRange, System.DateTime dtStartDate, System.DateTime dtEndDate, int intImageType, int intSize, int intLanguage) {
            this.SearchImageAsync(intID, strIDs, strTitle, strDesc, intCountryID, intSubjectID, blIsDateRange, dtStartDate, dtEndDate, intImageType, intSize, intLanguage, null);
        }
        
        /// <remarks/>
        public void SearchImageAsync(int intID, string strIDs, string strTitle, string strDesc, int intCountryID, int intSubjectID, bool blIsDateRange, System.DateTime dtStartDate, System.DateTime dtEndDate, int intImageType, int intSize, int intLanguage, object userState) {
            if ((this.SearchImageOperationCompleted == null)) {
                this.SearchImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchImageOperationCompleted);
            }
            this.InvokeAsync("SearchImage", new object[] {
                        intID,
                        strIDs,
                        strTitle,
                        strDesc,
                        intCountryID,
                        intSubjectID,
                        blIsDateRange,
                        dtStartDate,
                        dtEndDate,
                        intImageType,
                        intSize,
                        intLanguage}, this.SearchImageOperationCompleted, userState);
        }
        
        private void OnSearchImageOperationCompleted(object arg) {
            if ((this.SearchImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchImageCompleted(this, new SearchImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddEditFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddEditFile(System.Data.DataSet dsFile) {
            object[] results = this.Invoke("AddEditFile", new object[] {
                        dsFile});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddEditFileAsync(System.Data.DataSet dsFile) {
            this.AddEditFileAsync(dsFile, null);
        }
        
        /// <remarks/>
        public void AddEditFileAsync(System.Data.DataSet dsFile, object userState) {
            if ((this.AddEditFileOperationCompleted == null)) {
                this.AddEditFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEditFileOperationCompleted);
            }
            this.InvokeAsync("AddEditFile", new object[] {
                        dsFile}, this.AddEditFileOperationCompleted, userState);
        }
        
        private void OnAddEditFileOperationCompleted(object arg) {
            if ((this.AddEditFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEditFileCompleted(this, new AddEditFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteFile(int intFileID) {
            this.Invoke("DeleteFile", new object[] {
                        intFileID});
        }
        
        /// <remarks/>
        public void DeleteFileAsync(int intFileID) {
            this.DeleteFileAsync(intFileID, null);
        }
        
        /// <remarks/>
        public void DeleteFileAsync(int intFileID, object userState) {
            if ((this.DeleteFileOperationCompleted == null)) {
                this.DeleteFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileOperationCompleted);
            }
            this.InvokeAsync("DeleteFile", new object[] {
                        intFileID}, this.DeleteFileOperationCompleted, userState);
        }
        
        private void OnDeleteFileOperationCompleted(object arg) {
            if ((this.DeleteFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchFile(int intID, string strIDs, string strTitle, string strDesc, int intCountryID, int intSubjectID, bool blIsDateRange, System.DateTime dtStartDate, System.DateTime dtEndDate, int intFileType) {
            object[] results = this.Invoke("SearchFile", new object[] {
                        intID,
                        strIDs,
                        strTitle,
                        strDesc,
                        intCountryID,
                        intSubjectID,
                        blIsDateRange,
                        dtStartDate,
                        dtEndDate,
                        intFileType});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchFileAsync(int intID, string strIDs, string strTitle, string strDesc, int intCountryID, int intSubjectID, bool blIsDateRange, System.DateTime dtStartDate, System.DateTime dtEndDate, int intFileType) {
            this.SearchFileAsync(intID, strIDs, strTitle, strDesc, intCountryID, intSubjectID, blIsDateRange, dtStartDate, dtEndDate, intFileType, null);
        }
        
        /// <remarks/>
        public void SearchFileAsync(int intID, string strIDs, string strTitle, string strDesc, int intCountryID, int intSubjectID, bool blIsDateRange, System.DateTime dtStartDate, System.DateTime dtEndDate, int intFileType, object userState) {
            if ((this.SearchFileOperationCompleted == null)) {
                this.SearchFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchFileOperationCompleted);
            }
            this.InvokeAsync("SearchFile", new object[] {
                        intID,
                        strIDs,
                        strTitle,
                        strDesc,
                        intCountryID,
                        intSubjectID,
                        blIsDateRange,
                        dtStartDate,
                        dtEndDate,
                        intFileType}, this.SearchFileOperationCompleted, userState);
        }
        
        private void OnSearchFileOperationCompleted(object arg) {
            if ((this.SearchFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchFileCompleted(this, new SearchFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegisterCustomerCompletedEventHandler(object sender, RegisterCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UploadDataCompletedEventHandler(object sender, UploadDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UploadSiteReadingsCompletedEventHandler(object sender, UploadSiteReadingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSiteReadingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSiteReadingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddEditContentCompletedEventHandler(object sender, AddEditContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEditContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEditContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteContentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SearchContentCompletedEventHandler(object sender, SearchContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddEditPageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeletePageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SearchPageCompletedEventHandler(object sender, SearchPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddEditImageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteImageCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SearchImageCompletedEventHandler(object sender, SearchImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddEditFileCompletedEventHandler(object sender, AddEditFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddEditFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddEditFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DeleteFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SearchFileCompletedEventHandler(object sender, SearchFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591